sonar.projectKey=Tecnologia
sonar.projectName=Tecnologia
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_15b5814e0338b17b47a88a690dde9e092b77925a

sonar.sourceEncoding=UTF-8
sonar.sources=applications,domain,infrastructure
sonar.tests=applications/src/test,domain/src/test,infrastructure/src/test

sonar.java.binaries=**/build/classes/java/main
sonar.junit.reportsPath=**/build/test-results/test
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacocoMergedReport/jacocoMergedReport.xml
