server:
  port: 8088
spring:
  application:
    name: "Tecnologia"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"
#adapters:
#  r2dbc:
#    host: "${SPRING_R2DBC_HOST:tecnologia-db}"
#    port: "${SPRING_R2DBC_PORT:5432}"
#    database: "${SPRING_R2DBC_DATABASE:tecnologia}"
#    schema: "${SPRING_R2DBC_SCHEMA:public}"
#    username: "${SPRING_R2DBC_USERNAME:postgres}"
#    password: "${SPRING_R2DBC_PASSWORD:postgres}"

routers:
  paths:
    technologies: "/api/v1/tecnologias"

adapters:
  r2dbc:
    host: "localhost"
    port: "5432"
    database: "tecnologia"
    schema: "public"
    username: "postgres"
    password: "postgres"